export default {
  ADD_GIFT_TO_CART_SUCCESS: "ADD_GIFT_TO_CART_SUCCESS",
  ADD_GIFT_TO_CART_FAILED: "ADD_GIFT_TO_CART_FAILED",
  REMOVE_GIFT_FROM_CART_SUCCESS: "REMOVE_GIFT_FROM_CART_SUCCESS",
  SELL_CURRENCY: "SELL_CURRENCY",
  BUY_CURRENCY: "BUY_CURRENCY",
}
