export default {
  ADD_GIFT_TO_CART_SUCCESS: "ADD_GIFT_TO_CART_SUCCESS",
  ADD_GIFT_TO_CART_FAILED: "ADD_GIFT_TO_CART_FAILED",
  REMOVE_GIFT_FROM_CART_SUCCESS: "REMOVE_GIFT_FROM_CART_SUCCESS",
  SHOW_LOVE_EXCHANGE_MODAL: "SHOW_LOVE_EXCHANGE_MODAL",
  HIDE_LOVE_EXCHANGE_MODAL: "HIDE_LOVE_EXCHANGE_MODAL",
}
